### ISSUE TITLE
Beds duplicate

### ISSUE THREAD

**Issue by Slackow** [tryashtar/minecraft-stuff#2]
if you place a bed in front of a piston for every block it extends, it will make a new bed.

**Comment by tryashtar** [comment]
Thank you. I have fixed this by making the following blocks unpushable:
```sunflower, lilac, rose_bush, peony, tall_grass, large_fern, iron_door, oak_door, spruce_door, birch_door, jungle_door, acacia_door, dark_oak_door, white_bed, orange_bed, magenta_bed, light_blue_bed, yellow_bed, lime_bed, pink_bed, gray_bed, light_gray_bed, cyan_bed, purple_bed, blue_bed, brown_bed, green_bed, red_bed, black_bed, tall_seagrass```

Also, chests and trapped chests are no longer pushable unless they are single.
