### ISSUE TITLE
I need some help adjusting the extended pistons mod a little.

### ISSUE THREAD

**Issue by gentlewatcher** [tryashtar/minecraft-stuff#3]
I am just adding a few fun features for my own use for my world, and need some help, where is the trigger for the pull.mcfunction, I have gone through pretty much all the files and just cant find what triggers the pull function ( I just want to add in a use case where it triggers a modified version of the pull function and not the main one).

**Comment by tryashtar** [comment]
Specifically this line begins pulling:
https://github.com/tryashtar/datapacks/blob/c8c97c6b2688748c1f70e398acf93649782d37f9/ExtendedPistons/data/tryashtar.extended_pistons/functions/piston_arm/head_located.mcfunction#L9

(my apologies for the delayed answer; I don't seem to get notified of issues)
