### ISSUE TITLE
Dyeable Ender Chest Stations can't be pushed (Armorstands that make it work glitch out and don't move with it, also, when using one, if you punch/remove the chest on top, the dye detection/chest summoning completely breaks, thus deactivating the pack).

### ISSUE THREAD

**Issue by EnderHater** [tryashtar/minecraft-stuff#9]
Title says it all.

**Comment by tryashtar** [comment]
Thanks for the report. I _thought_ I had made extended pistons unable to push the chest stations, but I'll have to check.
And again about punching the chest, there's no real way to fix that. Since it's invulnerable in survival mode, there's no issue.

**Comment by EnderHater** [comment]
> Thanks for the report. I _thought_ I had made extended pistons unable to push the chest stations, but I'll have to check.
> And again about punching the chest, there's no real way to fix that. Since it's invulnerable in survival mode, there's no issue.

You could simply detect if the chest was punched by a player in creative mode, then resummon it.
